---
- name: Install the syzygyauthenticator from github
  git:
    repo: '{{ syzygyauthenticator_repo }}'
    dest: '{{ syzygyauthenticator_dir }}'
    version: '{{ syzygyauthenticator_version }}'

- name: Install the syzygyauthenticator
  pip:
    name: '{{ syzygyauthenticator_dir }}'
    executable: pip3.6
