# Stash of information we want to retain on the ansible client (e.g. certs)
secret: "{{ inventory_dir | realpath }}/.hostfiles/secret"
secret_host: "{{ secret }}/{{ inventory_hostname }}"
secret_host_directories:
  - name: 'acme_secrets'
    path: 'acme'
  - name: 'shib_secrets'
    path: 'shib'

