# =========================================================================
#                       GENERAL CONFIG
# =========================================================================
# Provide a key, value pair where the key is the course name, and the value is
# a list of its different sections
# EXAMPLE: "COURSE_GROUP_NAME": ["COURSE_SECTION_NAME_01", "COURSE_SECTION_NAME_02"]

course_groups:
  course_dsci_100_test:
  - section_dsci_100_test_01

# =========================================================================
lms_classes:
  course_dsci_100_test: rudaux.interface.Canvas

# =========================================================================
gs_classes:
  course_dsci_100_test: rudaux.interface.NBGrader

# =========================================================================
ss_classes:
  course_dsci_100_test: rudaux.interface.remote_zfs.RemoteZFSSubmissions

# =========================================================================
#                       CANVAS CONFIG
# =========================================================================

canvas_base_domain: https://canvas.ubc.ca
# =========================================================================
# Provide a key, value pair where the key is the course section name, and the value is
# the canvas id of that course section
# EXAMPLE: COURSE_SECTION_NAME_01": "12345"

canvas_course_lms_ids:
  section_dsci_100_test_01: '92197'

# =========================================================================
canvas_registration_deadlines:
  # YYYY-MM-DD
  section_dsci_100_test_01: '2022-10-30'

# =========================================================================
canvas_api_tokens:
  section_dsci_100_test_01: 11224~DBxLb0Bnhavc4UHQb1FxAIBGaEpXLyW1Ul1gbL0RU430rkSxUd5Rc7MOyjRlCeLQ

# =========================================================================
#                       ZFS CONFIG
# =========================================================================

remote_zfs_hostname:
  course_dsci_100_test: "dsci-100-student-test.stat.ubc.ca"

remote_zfs_port:
  course_dsci_100_test: "22"

remote_zfs_username:
  course_dsci_100_test: "stty2u"

remote_zfs_tz:
  course_dsci_100_test: "America/Vancouver"

remote_zfs_file_system_root:
  course_dsci_100_test: "tank/home/dsci100"

remote_zfs_path:
  course_dsci_100_test: "/usr/sbin/zfs" # remember to use this

#remote_zfs_volume_pattern: "str"
#remote_zfs_collection_pattern: "str"
#remote_zfs_distribution_pattern: "str"

# =========================================================================

# specify which user is the instructor (who to notify to post grades)
nbgrader_instructor_user: 'grader_jupyterhub_username_A'
# specify where to find the jupyterhub config directory (rudaux manages grading jupyterhub accounts)
nbgrader_jupyterhub_config_dir: '/srv/jupyterhub/'
# specify the linux user and group to grant ownership for grading directories (the jupyterhub user)
nbgrader_jupyterhub_user: 'jupyter'
nbgrader_jupyterhub_group: 'users'
# specify the quota to give grading accounts
# defaults to 5 gigabytes, but you can make this larger/smaller as needed
nbgrader_user_quota: '5g'
# specify where to create new grading folders (path to the directory where the jupyterhub user folders are stored)
nbgrader_user_root: '/path/to/jhub/user/folder/dir'
# specify the names of submitted/feedback/autograded folders
# you probably don't need to change these
nbgrader_submissions_folder: 'submitted'
nbgrader_feedback_folder: 'feedback'
nbgrader_autograded_folder: 'autograded'
# the amount of memory to give each autograding container
nbgrader_docker_memory: '2g'
# the image to use for nbgrader operations
# the example below is for the 0.17.0 version of the DSCI100 image
nbgrader_docker_image: 'ubcdsci/r-dsci-grading:v0.17.0'
# the name of the directory in the container to bind to the grader's jhub folder
nbgrader_docker_bind_folder: '/home/jupyter'
nbgrader_zfs_path: "/usr/sbin/zfs"


# the ssh-access git repository URL (the root of this directory should be an 'nbgrader' dir)
instructor_repo_url: 'git@github.com/your-instructor-repo.git'
# the path in each student's JHub directory to look for their assignment folders
# e.g. if assignment_name_1's folder is located at dsci-100-student/materials/assignment_name_1/...
# within each student's jhub user folder (and similar for the other assignments),
# this would be "dsci-100-student/materials"
student_local_assignment_folder: 'dsci-100-student/materials'
# the prefix to add to user folders (nbgrader breaks with student folders that are just numbers, so append student-##### to make it work)
# this can be essentially anything as long as it starts with a letter, so you probably don't need to change this
nbgrader_student_folder_prefix: 'student-'
# the fraction of deadlines that must be passed before solutions are returned (useful for early weeks in a semester with lots of auto late extensions)
return_solution_threshold: 0.93
# the earliest date to return solutions to anything regardless of the return thresholds
earliest_solution_return_date: '2021-09-26'

# =========================================================================
assignments:
  course_dsci_100_test:
    test_assignment:
    - grader_jhub_username_A

# =========================================================================
latereg_extension_days:
  course_dsci_100_test: 7

# =========================================================================
notify_timezone:
    course_dsci_100_test: America/Vancouver

# =========================================================================
autoext_cron_string: "* * * * *"
snap_cron_string: "* * * * *"
grade_cron_string: "* * * * *"

# =========================================================================