- name: ansible
  src: https://github.com/geerlingguy/ansible-role-ansible
  version: 1.3.0

- name: apache
  src: git+https://github.com/geerlingguy/ansible-role-apache.git
  version: 2.1.1

- name: docker
  src: https://github.com/geerlingguy/ansible-role-docker
  version: 2.1.0

- name: firewalld
  src: https://github.com/marcelnijenhof/ansible-role-firewalld.git

- name: sshd
  src: git+https://github.com/willshersystems/ansible-sshd.git
  version: v0.7.6

- name: sudo
  src:  https://github.com/weareinteractive/ansible-sudo
  version: 1.7.1
