---
- name: Set facts for secret location
  set_fact: 
    '{{ item.name }}': '{{ secret }}/{{ item.path }}'
  become: False
  delegate_to: 'localhost'
  with_items: "{{ secret_directories }}"
  when: secret_directories and item
  changed_when: False

- name: Set facts for host specific secret location
  set_fact: 
    '{{ item.name }}': '{{ secret_host }}/{{ item.path }}'
  become: False
  delegate_to: 'localhost'
  with_items: "{{ secret_host_directories }}"
  when: secret_host_directories and item
  changed_when: False

- name: Create secret directories on Ansible Controller
  file:
    path: '{{ secret }}/{{ item.path }}'
    state: 'directory'
  become: False
  delegate_to: 'localhost'
  with_items: "{{ secret_directories }}"
  when: secret_directories and item
  changed_when: False

- name: Create secret host specific directories on Ansible Controller
  file:
    path: '{{ secret_host }}/{{ item.path }}'
    state: 'directory'
  become: False
  delegate_to: 'localhost'
  with_items: "{{ secret_host_directories }}"
  when: secret_host_directories and item
  changed_when: False
