---
# Path to a directory in which a relative secret directory will be created.
# By default, it will be relative to Ansible inventory
secret_root: '{{ inventory_dir | realpath }}'

# Name of the directory which contains secrets. It will be in the form
# "secret" by default
secret_name: 'secret'

# How many directory levels to add relative to secret_root, by default 1 level.
# For example, to go 2 levels up, set this variable to '../..'
secret_levels: '..'

# Absolute path to directory with secrets. It will be configured as relative to
# current inventory directory. Use this variable in file and password lookups
secret: '{{ secret_root + "/" + ((secret_levels + "/")
            if secret_levels else "") + secret_name }}'

# Secret subrdirectories (created below {{ secret }})
secret_directories:
  - name: 'ssl'
    path: 'ssl'

# Same thing as above, but for host specific stuff
secret_host: '{{ secret }}/{{ inventory_hostname }}'
secret_host_directories:
  - name: 'deploy_keys'
    path: 'deploy_keys'
